# yml配置elasticsearch客户端地址（可配置项有限）
spring:
  elasticsearch:
#    path-prefix: SpringData/src/main/resources/http_ca.crt
    uris: https://192.168.38.131:9200 # elasticsearch 连接地址
    username: elastic # 用户名
    password: elastic # 密码
    connection-timeout: 10s # 连接超时时间（默认1s）

# 方便查询发送的http请求详细内容
logging:
  level:
    root: info
    org.springframework.data.elasticsearch.client.WIRE: trace

