server:
  port: 3344
eureka:
  instance:
    instance-id: cloud-config-center
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #github上的git仓库的名字
          uri: https://github.com/sakanal/springcloud-config.git
#          uri: git@github.com:sakanal/springcloud-config.git
#          uri: https://github.com/zzyybs/springcloud-config.git
          #搜索目录
          search-paths:
            - springcloud-config
#          username: sakanal
#          password: Githubqaz360782
      #读取分支
      label: main
#      label: master
  ##rabbitmq相关配置<--------------------------
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest


##rabbitmq相关配置,暴露bus刷新配置的端点<--------------------------
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'